=== kr0n4ik/L2JS/data/xsd/route.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="route">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="node" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:byte" name="id" use="optional" />
											<xs:attribute type="xs:int" name="fstring_index" use="optional" />
											<xs:attribute type="xs:byte" name="social_number" use="optional" />
											<xs:attribute type="xs:byte" name="delay" use="optional" />
											<xs:attribute type="xs:int" name="x" use="optional" />
											<xs:attribute type="xs:int" name="y" use="optional" />
											<xs:attribute type="xs:short" name="z" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="alias" />
						<xs:attribute type="xs:string" name="move_type" />
						<xs:attribute type="xs:boolean" name="isRunning" />
						<xs:attribute type="xs:boolean" name="cycling" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== kr0n4ik/L2JS/data/routes/trajan107.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/route.xsd">
	<route alias="trajan107" move_type="MoveSuperPoint_FollowRail" isRunning="true">
		<node id="0" x="184428" y="-180868" z="-3744" />
		<node id="1" x="184245" y="-179317" z="-3576" />
		<node id="2" x="186461" y="-179367" z="-3584" />
		<node id="3" x="186108" y="-181465" z="-3384" />
		<node id="4" x="187079" y="-183187" z="-3264" />
		<node id="5" x="185656" y="-184182" z="-3312" />
		<node id="6" x="184011" y="-184102" z="-3296" />
		<node id="7" x="182014" y="-185198" z="-3504" />
		<node id="8" x="179751" y="-185034" z="-3504" />
		<node id="9" x="177624" y="-185039" z="-3800" />
		<node id="10" x="175039" y="-185405" z="-3792" />
	</route>
</list>

=== kr0n4ik/L2JS/data/routes/IceQueen_2F_Right.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/route.xsd">
	<route alias="IceQueen_2F_Right" move_type="MoveSuperPoint_FollowRail">
		<node id="0" x="116353" y="-115466" z="-10984" />
		<node id="1" x="116253" y="-115624" z="-10984" />
		<node id="2" x="115433" y="-116448" z="-10984" />
		<node id="3" x="115371" y="-116515" z="-11032" />
		<node id="4" x="115349" y="-116534" z="-11040" />
		<node id="5" x="115299" y="-116576" z="-11064" />
		<node id="6" x="114715" y="-116762" z="-11080" />
		<node id="7" x="114722" y="-116648" z="-11080" />
		<node id="8" x="114724" y="-116347" z="-11200" />
		<node id="9" x="114805" y="-114936" z="-11200" />
	</route>
</list>

=== kr0n4ik/L2JS/data/routes/lost_76.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/route.xsd">
	<route alias="lost_76" move_type="MoveSuperPoint_Random">
		<node id="0" x="21340" y="-11092" z="-2784" />
		<node id="1" x="21661" y="-11549" z="-2744" />
		<node id="2" x="22158" y="-10939" z="-2760" />
		<node id="3" x="21791" y="-10137" z="-2808" />
		<node id="4" x="21029" y="-9777" z="-2848" />
		<node id="5" x="20628" y="-10780" z="-2824" />
		<node id="6" x="20961" y="-11761" z="-2776" />
	</route>
</list>

=== kr0n4ik/L2JS/data/routes/anta07.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/route.xsd">
	<route alias="anta07" move_type="MoveSuperPoint_FollowRail" isRunning="true" cycling="true">
		<node id="0" x="147470" y="112233" z="-3720" />
		<node id="1" x="148062" y="112676" z="-3720" />
		<node id="2" x="148825" y="112787" z="-3720" />
		<node id="3" x="149111" y="114411" z="-3720" />
		<node id="4" x="149144" y="115414" z="-3720" />
		<node id="5" x="147399" y="116543" z="-3696" />
		<node id="6" x="146176" y="116041" z="-3720" />
		<node id="7" x="144933" y="115060" z="-3720" />
		<node id="8" x="145177" y="113945" z="-3720" />
		<node id="9" x="145195" y="113291" z="-3720" />
		<node id="10" x="146235" y="112582" z="-3720" />
		<node id="11" x="147183" y="112277" z="-3720" />
	</route>
</list>
